/*var countries = new Array();
var stateBox;
var matches = 0;

countries[0] = "Afghanistan";
countries[1] = "Åland Islands";
countries[2] = "Albania";
countries[3] = "Algeria";
countries[4] = "American Samoa";
countries[5] = "Andorra";
countries[6] = "Angola";
countries[7] = "Anguilla";
countries[8] = "Antarctica";
countries[9] = "Antigua And Barbud";
countries[10] = "Argentina";
countries[11] = "Armenia";
countries[12] = "Aruba";
countries[13] = "Australia";
countries[14] = "Austria";
countries[15] = "Azerbaijan";
countries[16] = "Bahamas";
countries[17] = "Bahrain";
countries[18] = "Bangladesh";
countries[19] = "Barbados";
countries[20] = "Belarus";
countries[21] = "Belgium";
countries[22] = "Belize";
countries[23] = "Benin";
countries[24] = "Bermuda";
countries[25] = "Bhutan";
countries[26] = "Bolivia";
countries[27] = "Bonaire, Sint Eustatius and Saba";
countries[28] = "Bosnia and Herzegovina";
countries[29] = "Botswana";
countries[30] = "Bouvet Island";
countries[31] = "Brazil";
countries[32] = "British Indian Ocean Territory";
countries[33] = "Brunei Darussalam";
countries[34] = "Bulgaria";
countries[35] = "Burkina Faso";
countries[36] = "Burundi";
countries[37] = "Cambodia";
countries[38] = "Cameroon";
countries[39] = "Canada";
countries[40] = "Cape Verde";
countries[41] = "Cayman Islands";
countries[42] = "Central African Republic";
countries[43] = "Chile";
countries[44] = "China";
countries[45] = "Christmas Island";
countries[46] = "Cocos (Keeling) Islands";
countries[47] = "Colombia";
countries[48] = "Comoros";
countries[49] = "Congo";
countries[50] = "Congo, the Democratic Republic of the";
countries[51] = "Cook Islands";
countries[52] = "Costa Rica";
countries[53] = "Côte d'Ivoire";
countries[54] = "Croatia";
countries[55] = "Cuba";
countries[56] = "Curaçao";
countries[57] = "Cyprus";
countries[58] = "Czech Republic";
countries[59] = "Denmark";
countries[60] = "Dominica";
countries[61] = "Dominican Republic";
countries[62] = "Ecuador";
countries[63] = "Egypt";
countries[64] = "El Salvador";
countries[65] = "Equatorial Guinea";
countries[66] = "Eritrea";
countries[67] = "Estonia";
countries[68] = "Ethiopia";
countries[69] = "Falkland Islands (Malvinas)";
countries[70] = "Faroe Islands";
countries[71] = "Fiji";
countries[72] = "Finland";
countries[73] = "France";
countries[74] = "French Guiana";
countries[75] = "French Polynesia";
countries[76] = "French Southern Territories";
countries[77] = "Gabon";
countries[78] = "Gambia";
countries[79] = "Georgia";
countries[80] = "Germany";
countries[81] = "Ghana";
countries[82] = "Gibraltar";
countries[83] = "Grenada";
countries[84] = "Guadeloupe";
countries[85] = "Guam";
countries[86] = "Guatemala";
countries[87] = "Guernsey";
countries[88] = "Guinea";
countries[89] = "Guinea-Bissau";
countries[90] = "Guyana";
countries[91] = "Haiti";
countries[92] = "Heard Island and McDonald Islands";
countries[93] = "Holy See (Vatican City State)";
countries[94] = "Honduras";
countries[95] = "Hong Kong";
countries[96] = "Hungary";
countries[97] = "Iceland";
countries[98] = "India";
countries[99] = "Indonesia";
countries[100] = "Iran, Islamic Republic of";
countries[101] = "Ireland";
countries[102] = "Isle of Man";
countries[103] = "Israel";
countries[104] = "Italy";
countries[105] = "Jamaica";
countries[106] = "Japan";
countries[107] = "Jersey";
countries[108] = "Jordan";
countries[109] = "Kenya";
countries[110] = "Kiribati";
countries[111] = "Korea, Democratic People's Republic of";
countries[112] = "Korea, Republic of";
countries[113] = "Kuwait";
countries[114] = "Lao People's Democratic Republic";
countries[115] = "Latvia";
countries[116] = "Lebanon";
countries[117] = "Lesotho";
countries[118] = "Liberia";
countries[119] = "Libyan Arab Jamahiriya";
countries[120] = "Liechtenstein";
countries[121] = "Lithuania";
countries[122] = "Luxembourg";
countries[123] = "Macao";
countries[124] = "Madagascar";
countries[125] = "Malawi";
countries[126] = "Malaysia";
countries[127] = "Maldives";
countries[128] = "Mali";
countries[129] = "Malta";
countries[130] = "Marshall Islands";
countries[131] = "Martinique";
countries[132] = "Mauritania";
countries[133] = "Mauritius";
countries[134] = "Mayotte";
countries[135] = "Mexico";
countries[136] = "Micronesia, Federated States of";
countries[137] = "Moldova, Republic of";
countries[138] = "Monaco";
countries[139] = "Montenegro";
countries[140] = "Montserrat";
countries[141] = "Morocco";
countries[142] = "Mozambique";
countries[143] = "Myanmar";
countries[144] = "Namibia";
countries[145] = "Nauru";
countries[146] = "Nepal";
countries[147] = "Netherlands";
countries[148] = "New Caledonia";
countries[149] = "New Zealand";
countries[150] = "Nicaragua";
countries[151] = "Niger";
countries[152] = "Nigeria";
countries[153] = "Niue";
countries[154] = "Norfolk Island";
countries[155] = "Northern Mariana Islands";
countries[156] = "Norway";
countries[157] = "Oman";
countries[158] = "Pakistan";
countries[159] = "Palau";
countries[160] = "Palestinian Territory, Occupied";
countries[161] = "Panama";
countries[162] = "Papua New Guinea";
countries[163] = "Paraguay";
countries[164] = "Peru";
countries[165] = "Philippines";
countries[166] = "Pitcairn";
countries[167] = "Poland";
countries[168] = "Portugal";
countries[169] = "Puerto Rico";
countries[170] = "Qatar";
countries[171] = "Réunion";
countries[172] = "Romania";
countries[173] = "Rwanda";
countries[174] = "Saint Barthélemy";
countries[175] = "Saint Helena";
countries[176] = "Saint Kitts and Nevis";
countries[177] = "Saint Lucia";
countries[178] = "Saint Martin (French Part)";
countries[179] = "Saint Pierre and Miquelon";
countries[180] = "Saint Vincent and the Grenadines";
countries[181] = "Samoa";
countries[182] = "San Marino";
countries[183] = "Sao Tome and Principe";
countries[184] = "Saudi Arabia";
countries[185] = "Senegal";
countries[186] = "Seychelles";
countries[187] = "Sierra Leone";
countries[188] = "Singapore";
countries[189] = "Sint Maarten (Dutch Part)";
countries[190] = "Slovakia";
countries[191] = "Slovenia";
countries[192] = "Solomon Islands";
countries[193] = "Somalia";
countries[194] = "South Africa";
countries[195] = "South Georgia and the South Sandwich Islands";
countries[196] = "South Sudan";
countries[197] = "Spain";
countries[198] = "Sri Lanka";
countries[199] = "Sudan";
countries[200] = "Suriname";
countries[201] = "Svalbard and Jan Mayen";
countries[203] = "Swaziland";
countries[204] = "Sweden";
countries[205] = "Switzerland";
countries[206] = "Syrian Arab Republic";
countries[207] = "Taiwan, Province of China";
countries[208] = "Tanzania, United Republic of";
countries[209] = "Thailand";
countries[210] = "Timor-Leste";
countries[211] = "Togo";
countries[212] = "Tokelau";
countries[213] = "Tonga";
countries[214] = "Trinidad and Tobago";
countries[215] = "Tunisia";
countries[216] = "Turkey";
countries[217] = "Turkmenistan";
countries[218] = "Turks and Caicos Islands";
countries[219] = "Tuvalu";
countries[220] = "Uganda";
countries[221] = "United Arab Emirates";
countries[222] = "United Kingdom";
countries[223] = "United States";
countries[224] = "United States Minor Outlying Islands";
countries[225] = "Uruguay";
countries[226] = "Vanuatu";
countries[227] = "Venezuela";
countries[228] = "Vietnam";
countries[229] = "Virgin Islands, British";
countries[230] = "Virgin Islands, U.S.";
countries[231] = "Wallis and Futuna";
countries[232] = "Western Sahara";
countries[233] = "Yemen";
countries[234] = "Zambia";
countries[235] = "Zimbabwe";
countries.sort();

function calcSuggestions(box) {

    if (matches > 0) {
        for (i = 0; i < matches; i++) {
            var element = document.getElementById("suggestion" + i);
            document.getElementById("suggestions").removeChild(element);
            suggestions.style.visibility = "hidden";
        }
        matches = 0;
    }
    stateBox = document.getElementById("state");
    for (i = 0; i < countries.length; i++) {
        if (countries[i].indexOf(stateBox.value) == 0 && stateBox.value != "") {
            var element = document.createElement("div");

            element.setAttribute("id", "suggestion" + matches);
            element.className = "suggestion";
            element.innerHTML = countries[i];
            element.setAttribute("onClick", "insertState(this)");
            suggestions.appendChild(element);
            matches++;
            suggestions.style.visibility = "visible";
        }
    }

    if (stateBox.value.indexOf("i") != -1) {
        alert("this works");
    }
}

function insertState(text) {
    stateBox = text.innerHTML;
    suggestions.style.visibility = "hidden";
    for (i = 0; i < matches; i++) {
        var element = document.getElementById("suggestion" + i);
        document.getElementById("suggestions").removeChild(element);
    }
    matches = 0;
}*/


$("#state").keyup(function () {
    alert("yay");
});

